services:
  - type: web
    name: global-entry-alerter
    region: oregon
    env: python
    plan: starter
    buildCommand: "./render-build.sh"
    startCommand: "poetry run global-entry-alerter"
    autoDeploy: true
    branch: main
    envVars:
      - fromGroup: global-entry-alerter